Implement PVE variant

diff --git a/scripts/lvm_backup b/scripts/lvm_backup
--- a/scripts/lvm_backup
+++ b/scripts/lvm_backup
@@ -47,6 +47,25 @@ check_fs() {
 	fi
 }
 
+get_vm_disk() {
+	local VMID=$3
+
+        VOLID=$(
+                qm config "${VMID}" |
+                awk '
+                /^(scsi0|virtio0|sata0):/ {
+                        sub(/^[^:]*: /,"")
+                        sub(/,.*/,"")
+                        print
+                        exit
+                }'
+        )
+
+        [ -n "${VOLID}" ] || return 1
+
+        pvesm path "${VOLID}"
+}
+
 pre_backup () {
 	if  [ `ps ax| grep ${1} | grep rsync | wc -l` -eq "0" ] ; then
 		if [ `mount | grep ${1}--snap | wc -l` -gt "0" ] ; then
@@ -57,6 +76,39 @@ pre_backup () {
 			VSIZE="1G"
 		fi
 		case ${DISKTYPE} in
+			pve)
+				if ! [ -d ${TMPDIR} ] ; then mkdir -p ${TMPDIR} ; fi
+				mkdir -p ${MOUNTPOINT}/${1}
+				ZVOL="get_vm_disk"
+				if [ -z "${ZVOL}" ]; then
+					logger -t ${PROGRAM} "unable to determine disk for VM ${HOSTNAME}"
+					return 1
+				fi
+				DATASET=${ZVOL#/dev/zvol/}
+				SNAPNAME="${1}-backuppc"
+				zfs snapshot ${DATASET}@${SNAPNAME}
+				CLONE="${DATASET}-${SNAPNAME}"
+				zfs clone \
+					${DATASET}@${SNAPNAME} \
+					${CLONE}
+				echo "${DATASET}" > ${TMPDIR}/${1}.dataset
+				echo "${CLONE}"   > ${TMPDIR}/${1}.clone
+				LOOPDEV="/dev/zvol/${CLONE}"
+				# let mapper settle device
+				sleep ${SLEEP}
+				kpartx -av ${LOOPDEV}
+				# let mapper settle device
+				sleep ${SLEEP}
+				LODEV=$(basename ${LOOPDEV})
+				ROOTPART=$(ls /dev/mapper/${LODEV}p* 2>/dev/null | head -1)
+				if [ -z "${ROOTPART}" ]; then
+					logger -t ${PROGRAM} "unable to find partition on ${DEV}"
+					return 1
+				fi
+				FS=$(check_fs ${ROOTPART})
+				MOUNT="${MOUNT} ${FS}"
+				${MOUNT} ${ROOTPART} ${MOUNTPOINT}/${1}
+				;;
 			kvm)
 				if ! [ -d ${TMPDIR} ] ; then mkdir -p ${TMPDIR} ; fi
 				mkdir -p ${MOUNTPOINT}/${1}
@@ -70,9 +122,14 @@ pre_backup () {
 				# let mapper settle device
 				sleep ${SLEEP}
 				LODEV=$(basename ${LOOPDEV})
-				FS=$(check_fs "/dev/mapper/${LODEV}p1")
+				ROOTPART=$(ls /dev/mapper/${LODEV}p* 2>/dev/null | head -1)
+				if [ -z "${ROOTPART}" ]; then
+					logger -t ${PROGRAM} "unable to find partition on ${DEV}"
+					return 1
+				fi
+				FS=$(check_fs ${ROOTPART})
 				MOUNT="${MOUNT} ${FS}"
-				${MOUNT} /dev/mapper/${LODEV}p1 ${MOUNTPOINT}/${1}
+				${MOUNT} ${ROOTPART} ${MOUNTPOINT}/${1}
 				;;
 			native)
 				# check if $1 is set to 'root'
@@ -109,6 +166,18 @@ post_backup () {
 	if [ `ps ax| grep ${1} | grep rsync | wc -l` -eq "0" ] ; then
 		umount ${MOUNTPOINT}/${1}
 		case ${DISKTYPE} in
+			pve)
+				DATASET=$(cat ${TMPDIR}/${1}.dataset)
+				CLONE=$(cat ${TMPDIR}/${1}.clone)
+				LOOPDEV="/dev/zvol/${CLONE}"
+				${UMOUNT} ${MOUNTPOINT}/${1}
+				kpartx -d ${LOOPDEV}
+				zfs destroy ${CLONE}
+				zfs destroy ${DATASET}@${1}-backuppc
+				rm -f \
+					${TMPDIR}/${1}.dataset \
+					${TMPDIR}/${1}.clone
+				;;
 			kvm)
 				DEVSTRING=$(echo $1 | sed "s/-/--/g")
 				LOOPDEV=$(losetup -a | grep ${DEVSTRING} | awk -F':' {'print $1'})
